{% set version = "4.25.3" %}
{% set name = "cyclopts" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cyclopts-{{ version }}.tar.gz
  sha256: 7d3a067bc7699a1a65fe2ea0b092a925855bb711a05adc1e65c5b9ba307acea4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - cyclopts = cyclopts.cli:app
  skip: true  # [py<310]

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python
    - attrs >=23.1.0
    - rich >=13.6.0
    - docstring_parser >=0.15,<4.0
    - rich-rst >=1.3.1,<3.0.0
    - typing_extensions >=4.8.0  # [py<311]
    - tomli >=2.0.0  # [py<311]
  run_constrained:
    # trio
    - trio >=0.10.0
    # yaml
    - pyyaml >=6.0.1
    # debug
    - ipdb >=0.13.9
    - line_profiler >=3.5.1

test:
  imports:
    - cyclopts
  commands:
    - pip check
    - cyclopts --help
  requires:
    - pip

about:
  summary: Intuitive, easy CLIs based on python type hints.
  description: |
    Cyclopts is a modern, easy-to-use command-line interface (CLI)
    framework that aims to provide an intuitive & efficient developer
    experience.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  home: https://github.com/BrianPugh/cyclopts
  dev_url: https://github.com/BrianPugh/cyclopts
  doc_url: https://cyclopts.readthedocs.io

extra:
  recipe-maintainers:
    - viridianmelody
