{% set version = "4.6.0" %}
{% set name = "cyclopts" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cyclopts-{{ version }}.tar.gz
  sha256: 483c4704b953ea6da742e8de15972f405d2e748d19a848a4d61595e8e5360ee5

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python
    - attrs >=23.1.0
    - rich >=13.6.0
    - docstring_parser >=0.15,<4.0
    - rich-rst >=1.3.1,<2.0.0
    - typing_extensions >=4.8.0  # [py<311]
    - tomli >=2.0.0  # [py<311]
test:
  requires:
    - pip
  imports:
    - cyclopts
  commands:
    - pip check

about:
  summary: Intuitive, easy CLIs based on python type hints.
  description: |
    Cyclopts is a modern, easy-to-use command-line interface (CLI)
    framework that aims to provide an intuitive & efficient developer
    experience.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  home: https://github.com/BrianPugh/cyclopts
  dev_url: https://github.com/BrianPugh/cyclopts
  doc_url: https://cyclopts.readthedocs.io/

extra:
  recipe-maintainers:
    - viridianmelody
